In [1]:
#!/usr/bin/env python2
# -*- coding: utf-8 -*-
"""
Created on Tue Nov 12 01:18:16 2019

@author: mauricio
"""

#from geopy.geocoders import Nominatim
import pandas as pd
#import time

#geolocator = Nominatim(user_agent="https://nominatim.openstreetmap.org/")

In [4]:
BD = pd.read_excel ('/home/diogenes/projects/cyberpunklabs.github.io/scripts/basesDatos/hortaliceres_nn.xlsx',
                    decimal=',') #for an earlier version of Excel, you may need to use the file extension of 'xls'


BD.columns = ['productor', 'direccion', 'telefono', 'geolocalizacion']
BD.head()

,productor,direccion,telefono,geolocalizacion
0,NN,Del Valle,NN,"-33.3920816,-70.6139342"
1,NN,Abate Juan Ignacio Molina 2010,NN,"-33.1881735132313,-70.6607013372956"
2,NN,Santa Filomena 32,NN,"-33.2188499,-70.6621747"
3,NN,PARCELA N° 47 PERALILLO,NN,"-33.3662105,-70.8240491"
4,NN,Parcela N 56B flor de Chile. Lampa,NN,"-33.294081,-70.8401138"

In [23]:
ruta_archivo = '/home/diogenes/projects/cyberpunklabs.github.io/scripts/basesDatos/hortaliceres_nn.datos'
icono = 'lechugaIcon'
sector = 'hortaliceres'

with open(ruta_archivo, 'w') as archivo_temporal:
    for productor in range(len(BD.productor)):
        entrada = u'// {}\nL.marker([{}], {{icon: {}}}).bindPopup(\'{}<br>{}\').addTo({});\n\n'\
        .format(BD.productor[productor].title(),
                BD.geolocalizacion[productor],
                icono,
                BD.direccion[productor].title(),
                BD.telefono[productor],
                sector) #.encode('utf-8').strip()
        
        archivo_temporal.write(entrada + '\n\n')

        
        
#L.marker([-32.4532208, -71.2499938], {icon: lechugaIcon}).bindPopup('This is Littleton, CO.').addTo(cities1),

In [2]:
BD = pd.read_excel ('/home/diogenes/projects/cyberpunklabs.github.io/scripts/basesDatos/farmacias.xlsx',
                    decimal=',') #for an earlier version of Excel, you may need to use the file extension of 'xls'


BD.columns = ['productor', 'direccion', 'telefono', 'geolocalizacion']
BD.head()

,productor,direccion,telefono,geolocalizacion
0,Farmacia Mendoza,Avenida Carrascal 4360 Quinta Normal,(2)27724436 - (2)27739831,"-33.4231529,-70.6925735"
1,Farmacias Reunidas,Avenida Nueva Providencia 2058,(2)22314342 - (9)98662062,"-33.4237595,-70.6113739"
2,Clínica Veterinaria Los Robles Oftalmología Ve...,Pedro León Ugalde 1197,(2)25440306 - (9)95456645,"-33.4580383,-70.6335373"
3,Centro Veterinario Bayona (veterinaria),Avenida Tomás Moro 1905,(2)22125103 - (2)22120478,"-33.4295769,-70.5545731"
4,Clínica Veterinaria La Rotonda (veterinaria),Vicuña Mackenna 8469,(2)22814656 - (2)22812934,"-33.5332947,-70.594223"

In [3]:
ruta_archivo = '/home/diogenes/projects/cyberpunklabs.github.io/scripts/basesDatos/farmacias.datos'
icono = 'cruzIcon'
sector = 'farmacias'

with open(ruta_archivo, 'w') as archivo_temporal:
    for productor in range(len(BD.productor)):
        entrada = u'// {}\nL.marker([{}], {{icon: {}}}).bindPopup(\'<b>{}</b><br>{}<br>tel: {}\').addTo({});'\
        .format(BD.productor[productor].title(),
                BD.geolocalizacion[productor],
                icono,
                BD.productor[productor],
                BD.direccion[productor].title(),
                BD.telefono[productor],
                sector) #.encode('utf-8').strip()
        
        archivo_temporal.write(entrada + '\n')

        
        
#L.marker([-32.4532208, -71.2499938], {icon: lechugaIcon}).bindPopup('This is Littleton, CO.').addTo(cities1),